<section class="col-sm-12">
	<h1 class="text-center">Select Connector</h1>
	<div class="col-sm-10 col-sm-offset-1 ">
        <p>Welcome to the claim account function. This webpage allows you to claim
        your account from your school district's directory system. Please select your 
        school district below.</p>
	</div>
</section>

<section class="col-sm-12">
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
            <?php
            echo $this->form($this->formyform, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
            ?>
        </div>
	</div>
</section>

