<section class="col-sm-12">
	<h1 class="text-center">NSAP Question Admin</h1>
	<div class="col-sm-10 col-sm-offset-1">
		<p>Please add any attributes and questions you wish to add below. You can also
		delete any questions you wish to replace. </p>
	</div>
</section>

<br>

<br>

<section class="col-sm-12">
	<div class="col-sm-3 col-sm-offset-5">
		<span class="glyphicon glyphicon-user"
			style="font-size: 147px; outline: 1px solid black;"
			aria-hidden="true"></span>
	</div>

	<br> <br />


	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">

			<div class="panel panel-default">
				<div class="panel-heading">Questions for Connector ID: <?php echo $this->conid ?> <button
						type="button" class="btn btn-info btn-xs" data-toggle="modal"
						style="float: right;" data-target="#myModal">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					</button>
				</div>
				<table class="table table-striped">
					<tr>
						<th>Question Attribute</th>
						<th>Question</th>
						<th><span style="float: right;"> Delete </span></th>
					</tr>
                <?php
                if (count($this->querydata) > 0) {
                    foreach ($this->querydata as $question) {
                        /**
                         *
                         * @var $question \Application\Model\Question
                         */
                        ?>
                     <tr>
						<td> <?php echo $question->attribute ?> </td>
						<td> <?php echo $question->question ?> </td>
						<td>
							<button type="button" class="btn btn-info btn-xs"
								data-toggle="modal" style="float: right;"
								data-target="#delQuestion-<?php echo $question->id;?>">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</button>

                	    <?php echo $this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->deleteQuestionForm);?>
						<div class="modal fade"
								id="delQuestion-<?php echo $question->id;?>" tabindex="-1"
								role="dialog" aria-labelledby="myModalLabel">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal"
												aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
											<h4 class="modal-title" id="myModalLabel">Delete Question</h4>
										</div>
										<div class="modal-body">
											<div class="row">
												<div class="col-sm-10 col-sm-offset-1">
													<p>Are you sure you want to delete the following question:</p>
													<p><?php echo $question->question ?></p>
				       								<?php
                        $this->deleteQuestionForm->setData(array(
                            'question-id' => $question->id
                        ));
                        echo $this->formCollection($this->deleteQuestionForm);
                        ?>
				       							</div>
											</div>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-default"
												data-dismiss="modal">Close</button>
											<button type="submit" name="submit" id="submitbutton"
												class="btn btn-primary submit-button has-spinner"
												value="Submit">Delete</button>
										</div>
									</div>
								</div>
							</div>
						<?php echo $this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->closeTag($this->deleteQuestionForm);?>
						</td>
					</tr>
                <?php
                    
}
                } else {
                    ?>
	<tr>
						<td colspan="3">No Questions defined. You can add a question with
							the "+" button</td>
					</tr>
	<?php
                }
                ?>
                </table>
			</div>
		</div>
	</div>
</section>

<!-- Modal -->
<?php echo $this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->formyform);?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">Add A Question</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
			       		<?php echo $this->formCollection($this->formyform); ?>
			       	</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" name="submit" id="submitbutton"
					class="btn btn-primary submit-button has-spinner" value="Submit">Submit</button>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->closeTag($this->formyform);?>




