<section class="col-sm-12">
	<h1 class="text-center">NSAP Question Admin</h1>
	<div class="col-sm-10 col-sm-offset-1">
        <p>Welcome to the question administrator page. Please select the connector you wish 
        to add questions to below. </p>
	</div>
</section>

<section class="col-sm-12">
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
            <?php
            echo $this->form($this->formyform, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
            ?>
        </div>
	</div>
</section>

