<?php
/**
 * EducationContent
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * EducationContent Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EducationContent implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'string',
        'learning_standard_reference' => '\Swagger\Client\Model\LearningStandardReference',
        'content_identifier' => 'string',
        'learning_resource_metadata_uri' => 'string',
        'short_description' => 'string',
        'description' => 'string',
        'additional_authors_indicator' => 'bool',
        'publisher' => 'string',
        'time_required' => 'string',
        'interactivity_style_type' => 'string',
        'content_class_type' => 'string',
        'use_rights_url' => 'string',
        'publication_date' => '\\DateTime',
        'publication_year' => 'int',
        'version' => 'string',
        'cost' => 'Number',
        'cost_rate_type' => 'string',
        'namespace' => 'string',
        'appropriate_grade_levels' => '\Swagger\Client\Model\EducationContentAppropriateGradeLevel[]',
        'appropriate_sexes' => '\Swagger\Client\Model\EducationContentAppropriateSex[]',
        'authors' => '\Swagger\Client\Model\EducationContentAuthor[]',
        'derivative_source_education_contents' => '\Swagger\Client\Model\EducationContentDerivativeSourceEducationContent[]',
        'derivative_source_learning_resource_metadata_ur_is' => '\Swagger\Client\Model\EducationContentDerivativeSourceLearningResourceMetadataURI[]',
        'derivative_source_ur_is' => '\Swagger\Client\Model\EducationContentDerivativeSourceURI[]',
        'languages' => '\Swagger\Client\Model\EducationContentLanguage[]',
        '_etag' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'learning_standard_reference' => 'learningStandardReference',
        'content_identifier' => 'contentIdentifier',
        'learning_resource_metadata_uri' => 'learningResourceMetadataURI',
        'short_description' => 'shortDescription',
        'description' => 'description',
        'additional_authors_indicator' => 'additionalAuthorsIndicator',
        'publisher' => 'publisher',
        'time_required' => 'timeRequired',
        'interactivity_style_type' => 'interactivityStyleType',
        'content_class_type' => 'contentClassType',
        'use_rights_url' => 'useRightsURL',
        'publication_date' => 'publicationDate',
        'publication_year' => 'publicationYear',
        'version' => 'version',
        'cost' => 'cost',
        'cost_rate_type' => 'costRateType',
        'namespace' => 'namespace',
        'appropriate_grade_levels' => 'appropriateGradeLevels',
        'appropriate_sexes' => 'appropriateSexes',
        'authors' => 'authors',
        'derivative_source_education_contents' => 'derivativeSourceEducationContents',
        'derivative_source_learning_resource_metadata_ur_is' => 'derivativeSourceLearningResourceMetadataURIs',
        'derivative_source_ur_is' => 'derivativeSourceURIs',
        'languages' => 'languages',
        '_etag' => '_etag'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'learning_standard_reference' => 'setLearningStandardReference',
        'content_identifier' => 'setContentIdentifier',
        'learning_resource_metadata_uri' => 'setLearningResourceMetadataUri',
        'short_description' => 'setShortDescription',
        'description' => 'setDescription',
        'additional_authors_indicator' => 'setAdditionalAuthorsIndicator',
        'publisher' => 'setPublisher',
        'time_required' => 'setTimeRequired',
        'interactivity_style_type' => 'setInteractivityStyleType',
        'content_class_type' => 'setContentClassType',
        'use_rights_url' => 'setUseRightsUrl',
        'publication_date' => 'setPublicationDate',
        'publication_year' => 'setPublicationYear',
        'version' => 'setVersion',
        'cost' => 'setCost',
        'cost_rate_type' => 'setCostRateType',
        'namespace' => 'setNamespace',
        'appropriate_grade_levels' => 'setAppropriateGradeLevels',
        'appropriate_sexes' => 'setAppropriateSexes',
        'authors' => 'setAuthors',
        'derivative_source_education_contents' => 'setDerivativeSourceEducationContents',
        'derivative_source_learning_resource_metadata_ur_is' => 'setDerivativeSourceLearningResourceMetadataUrIs',
        'derivative_source_ur_is' => 'setDerivativeSourceUrIs',
        'languages' => 'setLanguages',
        '_etag' => 'setEtag'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'learning_standard_reference' => 'getLearningStandardReference',
        'content_identifier' => 'getContentIdentifier',
        'learning_resource_metadata_uri' => 'getLearningResourceMetadataUri',
        'short_description' => 'getShortDescription',
        'description' => 'getDescription',
        'additional_authors_indicator' => 'getAdditionalAuthorsIndicator',
        'publisher' => 'getPublisher',
        'time_required' => 'getTimeRequired',
        'interactivity_style_type' => 'getInteractivityStyleType',
        'content_class_type' => 'getContentClassType',
        'use_rights_url' => 'getUseRightsUrl',
        'publication_date' => 'getPublicationDate',
        'publication_year' => 'getPublicationYear',
        'version' => 'getVersion',
        'cost' => 'getCost',
        'cost_rate_type' => 'getCostRateType',
        'namespace' => 'getNamespace',
        'appropriate_grade_levels' => 'getAppropriateGradeLevels',
        'appropriate_sexes' => 'getAppropriateSexes',
        'authors' => 'getAuthors',
        'derivative_source_education_contents' => 'getDerivativeSourceEducationContents',
        'derivative_source_learning_resource_metadata_ur_is' => 'getDerivativeSourceLearningResourceMetadataUrIs',
        'derivative_source_ur_is' => 'getDerivativeSourceUrIs',
        'languages' => 'getLanguages',
        '_etag' => 'getEtag'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id The unique identifier of the resource.
      * @var string
      */
    protected $id;
    
    /**
      * $learning_standard_reference A reference to the related LearningStandard resource.
      * @var \Swagger\Client\Model\LearningStandardReference
      */
    protected $learning_standard_reference;
    
    /**
      * $content_identifier The identifier of the content standard.
      * @var string
      */
    protected $content_identifier;
    
    /**
      * $learning_resource_metadata_uri The public web site address (URL), file, or ftp locator.
      * @var string
      */
    protected $learning_resource_metadata_uri;
    
    /**
      * $short_description A shortened description for reference.
      * @var string
      */
    protected $short_description;
    
    /**
      * $description A detailed description of the entity.
      * @var string
      */
    protected $description;
    
    /**
      * $additional_authors_indicator Indicates whether there are additional un-named authors. In a research report, this is often marked by the abbreviation \"et al\".
      * @var bool
      */
    protected $additional_authors_indicator;
    
    /**
      * $publisher The organization credited with publishing the resource.
      * @var string
      */
    protected $publisher;
    
    /**
      * $time_required Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience.
      * @var string
      */
    protected $time_required;
    
    /**
      * $interactivity_style_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
      * @var string
      */
    protected $interactivity_style_type;
    
    /**
      * $content_class_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
      * @var string
      */
    protected $content_class_type;
    
    /**
      * $use_rights_url The URL where the owner specifies permissions for using the resource.
      * @var string
      */
    protected $use_rights_url;
    
    /**
      * $publication_date The date on which this content was first published.
      * @var \\DateTime
      */
    protected $publication_date;
    
    /**
      * $publication_year The year at which this content was first published.
      * @var int
      */
    protected $publication_year;
    
    /**
      * $version The version identifier for the content.
      * @var string
      */
    protected $version;
    
    /**
      * $cost An amount that has to be paid or spent to buy or obtain the EducationContent.
      * @var Number
      */
    protected $cost;
    
    /**
      * $cost_rate_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
      * @var string
      */
    protected $cost_rate_type;
    
    /**
      * $namespace Namespace for the EducationContent.
      * @var string
      */
    protected $namespace;
    
    /**
      * $appropriate_grade_levels An unordered collection of educationContentAppropriateGradeLevels.  Grade levels for which this education content is applicable-if omitted, considered generally applicable.
      * @var \Swagger\Client\Model\EducationContentAppropriateGradeLevel[]
      */
    protected $appropriate_grade_levels;
    
    /**
      * $appropriate_sexes An unordered collection of educationContentAppropriateSexes.  Genders for which this education content is applicable-if omitted, considered generally applicable.
      * @var \Swagger\Client\Model\EducationContentAppropriateSex[]
      */
    protected $appropriate_sexes;
    
    /**
      * $authors An unordered collection of educationContentAuthors.  The individual credited with the creation of the resource.
      * @var \Swagger\Client\Model\EducationContentAuthor[]
      */
    protected $authors;
    
    /**
      * $derivative_source_education_contents An unordered collection of educationContentDerivativeSourceEducationContents.  A reference to the Education Content from which this Education Content was derived.
      * @var \Swagger\Client\Model\EducationContentDerivativeSourceEducationContent[]
      */
    protected $derivative_source_education_contents;
    
    /**
      * $derivative_source_learning_resource_metadata_ur_is An unordered collection of educationContentDerivativeSourceLearningResourceMetadataURIs.  A reference to the Learning Resource Metadata URI from which this Education Content was derived.
      * @var \Swagger\Client\Model\EducationContentDerivativeSourceLearningResourceMetadataURI[]
      */
    protected $derivative_source_learning_resource_metadata_ur_is;
    
    /**
      * $derivative_source_ur_is An unordered collection of educationContentDerivativeSourceURIs.  A reference to the URI from which this Education Content was derived.
      * @var \Swagger\Client\Model\EducationContentDerivativeSourceURI[]
      */
    protected $derivative_source_ur_is;
    
    /**
      * $languages An unordered collection of educationContentLanguages.  An indication of the languages in which the Education Content is designed.
      * @var \Swagger\Client\Model\EducationContentLanguage[]
      */
    protected $languages;
    
    /**
      * $_etag A unique system-generated value that identifies the version of the resource.
      * @var string
      */
    protected $_etag;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->learning_standard_reference = $data["learning_standard_reference"];
            $this->content_identifier = $data["content_identifier"];
            $this->learning_resource_metadata_uri = $data["learning_resource_metadata_uri"];
            $this->short_description = $data["short_description"];
            $this->description = $data["description"];
            $this->additional_authors_indicator = $data["additional_authors_indicator"];
            $this->publisher = $data["publisher"];
            $this->time_required = $data["time_required"];
            $this->interactivity_style_type = $data["interactivity_style_type"];
            $this->content_class_type = $data["content_class_type"];
            $this->use_rights_url = $data["use_rights_url"];
            $this->publication_date = $data["publication_date"];
            $this->publication_year = $data["publication_year"];
            $this->version = $data["version"];
            $this->cost = $data["cost"];
            $this->cost_rate_type = $data["cost_rate_type"];
            $this->namespace = $data["namespace"];
            $this->appropriate_grade_levels = $data["appropriate_grade_levels"];
            $this->appropriate_sexes = $data["appropriate_sexes"];
            $this->authors = $data["authors"];
            $this->derivative_source_education_contents = $data["derivative_source_education_contents"];
            $this->derivative_source_learning_resource_metadata_ur_is = $data["derivative_source_learning_resource_metadata_ur_is"];
            $this->derivative_source_ur_is = $data["derivative_source_ur_is"];
            $this->languages = $data["languages"];
            $this->_etag = $data["_etag"];
        }
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id The unique identifier of the resource.
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets learning_standard_reference
     * @return \Swagger\Client\Model\LearningStandardReference
     */
    public function getLearningStandardReference()
    {
        return $this->learning_standard_reference;
    }
  
    /**
     * Sets learning_standard_reference
     * @param \Swagger\Client\Model\LearningStandardReference $learning_standard_reference A reference to the related LearningStandard resource.
     * @return $this
     */
    public function setLearningStandardReference($learning_standard_reference)
    {
        
        $this->learning_standard_reference = $learning_standard_reference;
        return $this;
    }
    
    /**
     * Gets content_identifier
     * @return string
     */
    public function getContentIdentifier()
    {
        return $this->content_identifier;
    }
  
    /**
     * Sets content_identifier
     * @param string $content_identifier The identifier of the content standard.
     * @return $this
     */
    public function setContentIdentifier($content_identifier)
    {
        
        $this->content_identifier = $content_identifier;
        return $this;
    }
    
    /**
     * Gets learning_resource_metadata_uri
     * @return string
     */
    public function getLearningResourceMetadataUri()
    {
        return $this->learning_resource_metadata_uri;
    }
  
    /**
     * Sets learning_resource_metadata_uri
     * @param string $learning_resource_metadata_uri The public web site address (URL), file, or ftp locator.
     * @return $this
     */
    public function setLearningResourceMetadataUri($learning_resource_metadata_uri)
    {
        
        $this->learning_resource_metadata_uri = $learning_resource_metadata_uri;
        return $this;
    }
    
    /**
     * Gets short_description
     * @return string
     */
    public function getShortDescription()
    {
        return $this->short_description;
    }
  
    /**
     * Sets short_description
     * @param string $short_description A shortened description for reference.
     * @return $this
     */
    public function setShortDescription($short_description)
    {
        
        $this->short_description = $short_description;
        return $this;
    }
    
    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
  
    /**
     * Sets description
     * @param string $description A detailed description of the entity.
     * @return $this
     */
    public function setDescription($description)
    {
        
        $this->description = $description;
        return $this;
    }
    
    /**
     * Gets additional_authors_indicator
     * @return bool
     */
    public function getAdditionalAuthorsIndicator()
    {
        return $this->additional_authors_indicator;
    }
  
    /**
     * Sets additional_authors_indicator
     * @param bool $additional_authors_indicator Indicates whether there are additional un-named authors. In a research report, this is often marked by the abbreviation \"et al\".
     * @return $this
     */
    public function setAdditionalAuthorsIndicator($additional_authors_indicator)
    {
        
        $this->additional_authors_indicator = $additional_authors_indicator;
        return $this;
    }
    
    /**
     * Gets publisher
     * @return string
     */
    public function getPublisher()
    {
        return $this->publisher;
    }
  
    /**
     * Sets publisher
     * @param string $publisher The organization credited with publishing the resource.
     * @return $this
     */
    public function setPublisher($publisher)
    {
        
        $this->publisher = $publisher;
        return $this;
    }
    
    /**
     * Gets time_required
     * @return string
     */
    public function getTimeRequired()
    {
        return $this->time_required;
    }
  
    /**
     * Sets time_required
     * @param string $time_required Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience.
     * @return $this
     */
    public function setTimeRequired($time_required)
    {
        
        $this->time_required = $time_required;
        return $this;
    }
    
    /**
     * Gets interactivity_style_type
     * @return string
     */
    public function getInteractivityStyleType()
    {
        return $this->interactivity_style_type;
    }
  
    /**
     * Sets interactivity_style_type
     * @param string $interactivity_style_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
     * @return $this
     */
    public function setInteractivityStyleType($interactivity_style_type)
    {
        
        $this->interactivity_style_type = $interactivity_style_type;
        return $this;
    }
    
    /**
     * Gets content_class_type
     * @return string
     */
    public function getContentClassType()
    {
        return $this->content_class_type;
    }
  
    /**
     * Sets content_class_type
     * @param string $content_class_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
     * @return $this
     */
    public function setContentClassType($content_class_type)
    {
        
        $this->content_class_type = $content_class_type;
        return $this;
    }
    
    /**
     * Gets use_rights_url
     * @return string
     */
    public function getUseRightsUrl()
    {
        return $this->use_rights_url;
    }
  
    /**
     * Sets use_rights_url
     * @param string $use_rights_url The URL where the owner specifies permissions for using the resource.
     * @return $this
     */
    public function setUseRightsUrl($use_rights_url)
    {
        
        $this->use_rights_url = $use_rights_url;
        return $this;
    }
    
    /**
     * Gets publication_date
     * @return \\DateTime
     */
    public function getPublicationDate()
    {
        return $this->publication_date;
    }
  
    /**
     * Sets publication_date
     * @param \\DateTime $publication_date The date on which this content was first published.
     * @return $this
     */
    public function setPublicationDate($publication_date)
    {
        
        $this->publication_date = $publication_date;
        return $this;
    }
    
    /**
     * Gets publication_year
     * @return int
     */
    public function getPublicationYear()
    {
        return $this->publication_year;
    }
  
    /**
     * Sets publication_year
     * @param int $publication_year The year at which this content was first published.
     * @return $this
     */
    public function setPublicationYear($publication_year)
    {
        
        $this->publication_year = $publication_year;
        return $this;
    }
    
    /**
     * Gets version
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }
  
    /**
     * Sets version
     * @param string $version The version identifier for the content.
     * @return $this
     */
    public function setVersion($version)
    {
        
        $this->version = $version;
        return $this;
    }
    
    /**
     * Gets cost
     * @return Number
     */
    public function getCost()
    {
        return $this->cost;
    }
  
    /**
     * Sets cost
     * @param Number $cost An amount that has to be paid or spent to buy or obtain the EducationContent.
     * @return $this
     */
    public function setCost($cost)
    {
        
        $this->cost = $cost;
        return $this;
    }
    
    /**
     * Gets cost_rate_type
     * @return string
     */
    public function getCostRateType()
    {
        return $this->cost_rate_type;
    }
  
    /**
     * Sets cost_rate_type
     * @param string $cost_rate_type A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
     * @return $this
     */
    public function setCostRateType($cost_rate_type)
    {
        
        $this->cost_rate_type = $cost_rate_type;
        return $this;
    }
    
    /**
     * Gets namespace
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }
  
    /**
     * Sets namespace
     * @param string $namespace Namespace for the EducationContent.
     * @return $this
     */
    public function setNamespace($namespace)
    {
        
        $this->namespace = $namespace;
        return $this;
    }
    
    /**
     * Gets appropriate_grade_levels
     * @return \Swagger\Client\Model\EducationContentAppropriateGradeLevel[]
     */
    public function getAppropriateGradeLevels()
    {
        return $this->appropriate_grade_levels;
    }
  
    /**
     * Sets appropriate_grade_levels
     * @param \Swagger\Client\Model\EducationContentAppropriateGradeLevel[] $appropriate_grade_levels An unordered collection of educationContentAppropriateGradeLevels.  Grade levels for which this education content is applicable-if omitted, considered generally applicable.
     * @return $this
     */
    public function setAppropriateGradeLevels($appropriate_grade_levels)
    {
        
        $this->appropriate_grade_levels = $appropriate_grade_levels;
        return $this;
    }
    
    /**
     * Gets appropriate_sexes
     * @return \Swagger\Client\Model\EducationContentAppropriateSex[]
     */
    public function getAppropriateSexes()
    {
        return $this->appropriate_sexes;
    }
  
    /**
     * Sets appropriate_sexes
     * @param \Swagger\Client\Model\EducationContentAppropriateSex[] $appropriate_sexes An unordered collection of educationContentAppropriateSexes.  Genders for which this education content is applicable-if omitted, considered generally applicable.
     * @return $this
     */
    public function setAppropriateSexes($appropriate_sexes)
    {
        
        $this->appropriate_sexes = $appropriate_sexes;
        return $this;
    }
    
    /**
     * Gets authors
     * @return \Swagger\Client\Model\EducationContentAuthor[]
     */
    public function getAuthors()
    {
        return $this->authors;
    }
  
    /**
     * Sets authors
     * @param \Swagger\Client\Model\EducationContentAuthor[] $authors An unordered collection of educationContentAuthors.  The individual credited with the creation of the resource.
     * @return $this
     */
    public function setAuthors($authors)
    {
        
        $this->authors = $authors;
        return $this;
    }
    
    /**
     * Gets derivative_source_education_contents
     * @return \Swagger\Client\Model\EducationContentDerivativeSourceEducationContent[]
     */
    public function getDerivativeSourceEducationContents()
    {
        return $this->derivative_source_education_contents;
    }
  
    /**
     * Sets derivative_source_education_contents
     * @param \Swagger\Client\Model\EducationContentDerivativeSourceEducationContent[] $derivative_source_education_contents An unordered collection of educationContentDerivativeSourceEducationContents.  A reference to the Education Content from which this Education Content was derived.
     * @return $this
     */
    public function setDerivativeSourceEducationContents($derivative_source_education_contents)
    {
        
        $this->derivative_source_education_contents = $derivative_source_education_contents;
        return $this;
    }
    
    /**
     * Gets derivative_source_learning_resource_metadata_ur_is
     * @return \Swagger\Client\Model\EducationContentDerivativeSourceLearningResourceMetadataURI[]
     */
    public function getDerivativeSourceLearningResourceMetadataUrIs()
    {
        return $this->derivative_source_learning_resource_metadata_ur_is;
    }
  
    /**
     * Sets derivative_source_learning_resource_metadata_ur_is
     * @param \Swagger\Client\Model\EducationContentDerivativeSourceLearningResourceMetadataURI[] $derivative_source_learning_resource_metadata_ur_is An unordered collection of educationContentDerivativeSourceLearningResourceMetadataURIs.  A reference to the Learning Resource Metadata URI from which this Education Content was derived.
     * @return $this
     */
    public function setDerivativeSourceLearningResourceMetadataUrIs($derivative_source_learning_resource_metadata_ur_is)
    {
        
        $this->derivative_source_learning_resource_metadata_ur_is = $derivative_source_learning_resource_metadata_ur_is;
        return $this;
    }
    
    /**
     * Gets derivative_source_ur_is
     * @return \Swagger\Client\Model\EducationContentDerivativeSourceURI[]
     */
    public function getDerivativeSourceUrIs()
    {
        return $this->derivative_source_ur_is;
    }
  
    /**
     * Sets derivative_source_ur_is
     * @param \Swagger\Client\Model\EducationContentDerivativeSourceURI[] $derivative_source_ur_is An unordered collection of educationContentDerivativeSourceURIs.  A reference to the URI from which this Education Content was derived.
     * @return $this
     */
    public function setDerivativeSourceUrIs($derivative_source_ur_is)
    {
        
        $this->derivative_source_ur_is = $derivative_source_ur_is;
        return $this;
    }
    
    /**
     * Gets languages
     * @return \Swagger\Client\Model\EducationContentLanguage[]
     */
    public function getLanguages()
    {
        return $this->languages;
    }
  
    /**
     * Sets languages
     * @param \Swagger\Client\Model\EducationContentLanguage[] $languages An unordered collection of educationContentLanguages.  An indication of the languages in which the Education Content is designed.
     * @return $this
     */
    public function setLanguages($languages)
    {
        
        $this->languages = $languages;
        return $this;
    }
    
    /**
     * Gets _etag
     * @return string
     */
    public function getEtag()
    {
        return $this->_etag;
    }
  
    /**
     * Sets _etag
     * @param string $_etag A unique system-generated value that identifies the version of the resource.
     * @return $this
     */
    public function setEtag($_etag)
    {
        
        $this->_etag = $_etag;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
