<?php
/**
 * RestraintEvent
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * RestraintEvent Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RestraintEvent implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'string',
        'school_reference' => '\Swagger\Client\Model\SchoolReference',
        'student_reference' => '\Swagger\Client\Model\StudentReference',
        'identifier' => 'string',
        'event_date' => '\\DateTime',
        'educational_environment_type' => 'string',
        'programs' => '\Swagger\Client\Model\RestraintEventProgram[]',
        'reasons' => '\Swagger\Client\Model\RestraintEventReason[]',
        '_etag' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'school_reference' => 'schoolReference',
        'student_reference' => 'studentReference',
        'identifier' => 'identifier',
        'event_date' => 'eventDate',
        'educational_environment_type' => 'educationalEnvironmentType',
        'programs' => 'programs',
        'reasons' => 'reasons',
        '_etag' => '_etag'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'school_reference' => 'setSchoolReference',
        'student_reference' => 'setStudentReference',
        'identifier' => 'setIdentifier',
        'event_date' => 'setEventDate',
        'educational_environment_type' => 'setEducationalEnvironmentType',
        'programs' => 'setPrograms',
        'reasons' => 'setReasons',
        '_etag' => 'setEtag'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'school_reference' => 'getSchoolReference',
        'student_reference' => 'getStudentReference',
        'identifier' => 'getIdentifier',
        'event_date' => 'getEventDate',
        'educational_environment_type' => 'getEducationalEnvironmentType',
        'programs' => 'getPrograms',
        'reasons' => 'getReasons',
        '_etag' => 'getEtag'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id The unique identifier of the resource.
      * @var string
      */
    protected $id;
    
    /**
      * $school_reference A reference to the related School resource.
      * @var \Swagger\Client\Model\SchoolReference
      */
    protected $school_reference;
    
    /**
      * $student_reference A reference to the related Student resource.
      * @var \Swagger\Client\Model\StudentReference
      */
    protected $student_reference;
    
    /**
      * $identifier A unique number or alphanumeric code assigned to a restraint event by a school, school system, a state, or other agency or entity.
      * @var string
      */
    protected $identifier;
    
    /**
      * $event_date Month, day, and year of the RestraintEvent.
      * @var \\DateTime
      */
    protected $event_date;
    
    /**
      * $educational_environment_type The setting where the restrint was exercised..
      * @var string
      */
    protected $educational_environment_type;
    
    /**
      * $programs An unordered collection of restraintEventPrograms.  The Special Education program associated with the restraint event.
      * @var \Swagger\Client\Model\RestraintEventProgram[]
      */
    protected $programs;
    
    /**
      * $reasons An unordered collection of restraintEventReasons.  The items of categorization of the circumstances or reasons for the restraint.
      * @var \Swagger\Client\Model\RestraintEventReason[]
      */
    protected $reasons;
    
    /**
      * $_etag A unique system-generated value that identifies the version of the resource.
      * @var string
      */
    protected $_etag;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->school_reference = $data["school_reference"];
            $this->student_reference = $data["student_reference"];
            $this->identifier = $data["identifier"];
            $this->event_date = $data["event_date"];
            $this->educational_environment_type = $data["educational_environment_type"];
            $this->programs = $data["programs"];
            $this->reasons = $data["reasons"];
            $this->_etag = $data["_etag"];
        }
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id The unique identifier of the resource.
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets school_reference
     * @return \Swagger\Client\Model\SchoolReference
     */
    public function getSchoolReference()
    {
        return $this->school_reference;
    }
  
    /**
     * Sets school_reference
     * @param \Swagger\Client\Model\SchoolReference $school_reference A reference to the related School resource.
     * @return $this
     */
    public function setSchoolReference($school_reference)
    {
        
        $this->school_reference = $school_reference;
        return $this;
    }
    
    /**
     * Gets student_reference
     * @return \Swagger\Client\Model\StudentReference
     */
    public function getStudentReference()
    {
        return $this->student_reference;
    }
  
    /**
     * Sets student_reference
     * @param \Swagger\Client\Model\StudentReference $student_reference A reference to the related Student resource.
     * @return $this
     */
    public function setStudentReference($student_reference)
    {
        
        $this->student_reference = $student_reference;
        return $this;
    }
    
    /**
     * Gets identifier
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }
  
    /**
     * Sets identifier
     * @param string $identifier A unique number or alphanumeric code assigned to a restraint event by a school, school system, a state, or other agency or entity.
     * @return $this
     */
    public function setIdentifier($identifier)
    {
        
        $this->identifier = $identifier;
        return $this;
    }
    
    /**
     * Gets event_date
     * @return \\DateTime
     */
    public function getEventDate()
    {
        return $this->event_date;
    }
  
    /**
     * Sets event_date
     * @param \\DateTime $event_date Month, day, and year of the RestraintEvent.
     * @return $this
     */
    public function setEventDate($event_date)
    {
        
        $this->event_date = $event_date;
        return $this;
    }
    
    /**
     * Gets educational_environment_type
     * @return string
     */
    public function getEducationalEnvironmentType()
    {
        return $this->educational_environment_type;
    }
  
    /**
     * Sets educational_environment_type
     * @param string $educational_environment_type The setting where the restrint was exercised..
     * @return $this
     */
    public function setEducationalEnvironmentType($educational_environment_type)
    {
        
        $this->educational_environment_type = $educational_environment_type;
        return $this;
    }
    
    /**
     * Gets programs
     * @return \Swagger\Client\Model\RestraintEventProgram[]
     */
    public function getPrograms()
    {
        return $this->programs;
    }
  
    /**
     * Sets programs
     * @param \Swagger\Client\Model\RestraintEventProgram[] $programs An unordered collection of restraintEventPrograms.  The Special Education program associated with the restraint event.
     * @return $this
     */
    public function setPrograms($programs)
    {
        
        $this->programs = $programs;
        return $this;
    }
    
    /**
     * Gets reasons
     * @return \Swagger\Client\Model\RestraintEventReason[]
     */
    public function getReasons()
    {
        return $this->reasons;
    }
  
    /**
     * Sets reasons
     * @param \Swagger\Client\Model\RestraintEventReason[] $reasons An unordered collection of restraintEventReasons.  The items of categorization of the circumstances or reasons for the restraint.
     * @return $this
     */
    public function setReasons($reasons)
    {
        
        $this->reasons = $reasons;
        return $this;
    }
    
    /**
     * Gets _etag
     * @return string
     */
    public function getEtag()
    {
        return $this->_etag;
    }
  
    /**
     * Sets _etag
     * @param string $_etag A unique system-generated value that identifies the version of the resource.
     * @return $this
     */
    public function setEtag($_etag)
    {
        
        $this->_etag = $_etag;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
