<section class="col-sm-12">
	<h1 class="text-center">Login</h1>
	<div class="col-sm-10 col-sm-offset-1">
		<p>Welcome to the Nebraska Schools Account Provisioning application. This system
        allows a user to claim an account and reset password. To enter the application,
        please select your school district's user directory below, and type in your 
        username and password. If you do not have access to the account, please click on
        the claim account tab above.</p>
	</div>
</section>

<section class="col-sm-12">
	<div class="col-sm-3 col-sm-offset-5">
		<span class="glyphicon glyphicon-user" style="font-size: 147px; outline: 1px solid black;" aria-hidden="true"></span>
	</div>
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
			<?php echo $this->form($this->loginForm, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL); ?>
		</div>
	</div>
</section>