<section class="col-sm-12">
	<h1 class="text-center">Add Connector</h1>
	<div class="col-sm-10 col-sm-offset-1">
        <p>This webpage will allow you to create a new connector to interface with your
		school district's directory system. To continue, please select your school district's 
		connector type below.</p>
	</div>
</section>

<section class="col-sm-12">
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
            <?php
            echo $this->form($this->formyform, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
            ?>
        </div>
	</div>
</section>

