<?php
use Application\Model\EdFiEntry;
/**
 *
 * @var $this \Zend\View\Helper\ViewModel
 */
/**
 *
 * @var $edfiEntries \Application\Model\EdFiEntry[]
 */
$edfiEntries = $this->edfiEntries;
/**
 *
 * @var \Applcation\Model\Connectors[]
 */
$connectors = $this->connectors;
?>

<section class="col-sm-12">
	<h1 class="text-center">EdFi Information Entry</h1>
	<div class="col-sm-10 col-sm-offset-1">
		<p>Welcome. This page will allow you to create and modify EdFi entries. To create an entry,
		please select if you want to sync students, staff, or both. Then create four patterns
		that will be used to create usernames in your user directory. Patterns can contain the following:
		{firstname}, {firstinitial}, {middlename}, {middleinitial}, {lastname}, {lastinitial}.
		As an example, {firstname}.{middleinitial}.{lastname} would output john.s.doe for John Sam Doe.
		Please also provide a notification email in case a username is not able to be created based
		on one of the four patterns. Finally, log in using your EdFi credentials.  </p>
	</div>
</section>
<section class="col-sm-12">
	<h2>
		Current EdFi Entries - <a href="#addNewEntryForm" data-toggle="modal"
			data-target="#addNewEntryForm">Add</a>
	</h2>
	<br />
	<?php
	//echo '<pre>' . print_r($this->addEdfiEntryForm, true) . '</pre>';

	echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->addEdfiEntryForm);
	?>
	<div class="modal fade" id="addNewEntryForm" tabindex="-1"
		role="dialog" aria-labelledby="addNewEntryFormLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title" id="myModalLabel">Add EdFi Definition</h4>
				</div>
				<div class="modal-body">
					<p>Please fill out the following information to tie a connector to
						a EdFi Entry.</p>
					<p>Pattern information may contain the following tokens


					<p>


					<ul>
						<li>{firstname}</li>
						<li>{firstinitial}</li>
						<li>{middlename}</li>
						<li>{middleinitial}</li>
						<li>{lastname}</li>
						<li>{lastinitial}</li>
					</ul>
					<p>An example of a pattern is the following
						{firstname}.{middleinitial}.{lastname} would output john.s.doe for
						John Sam Doe.</p>
				<?php
				echo $this->formCollection($this->addEdfiEntryForm);
				?></div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit"
						class="btn btn-primary submit-button has-spinner">Save changes</button>
				</div>
			</div>
		</div>
	</div>
	<?php
	echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->closeTag($this->addEdfiEntryForm);
	?>
</section>
<section class="col-sm-12">
	<?php foreach($edfiEntries as $edfiEntry){?>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $connectors[$edfiEntry->connector_id]->getHostname();?> (id:<?php echo $edfiEntry->connector_id;?>)


				 <a class="" style="float:right;"
					href="#deleteEdFiEntry-<?php echo $edfiEntry->getId();?>"
					data-toggle="modal"
					data-target="#deleteEdFiEntry-<?php echo  $edfiEntry->getId();?>"><span
					class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>

			</div>
			<table class="table table-striped">
				<tr>
					<th>Sync Students</th>
					<td><?php echo $edfiEntry->sync_students == 1 ? "Yes": "No";?></td>
				</tr>
				<tr>
					<th>Sync Staff</th>
					<td><?php echo $edfiEntry->sync_staff == 1 ? "Yes": "No";?></td>
				</tr>
				<tr>
					<th>Pattern 1</th>
					<td><?php echo $edfiEntry->pattern1;?></td>
				</tr>
				<tr>
					<th>Pattern 2</th>
					<td><?php echo $edfiEntry->pattern2;?></td>
				</tr>
				<tr>
					<th>Pattern 3</th>
					<td><?php echo $edfiEntry->pattern3;?></td>
				</tr>
				<tr>
					<th>Pattern 4</th>
					<td><?php echo $edfiEntry->pattern4;?></td>
				</tr>
				<tr>
					<th>Notification Email</th>
					<td><?php echo $edfiEntry->who_to_notify_on_fail;?></td>
				</tr>
				<tr>
					<th>EdFi Username</th>
					<td><?php echo $edfiEntry->edfi_username;?></td>
				</tr>
			</table>
		</div>
	</div>
	<?php
		$this->deleteEdFiEntryForm->setName("deleteEdFiEntry-" . $edfiEntry->getId() . "-form");
		echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($this->deleteEdFiEntryForm);
		?>
	<div class="modal fade"
		id="deleteEdFiEntry-<?php echo $edfiEntry->getId();?>" tabindex="-1"
		role="dialog"
		aria-labelledby="deleteEdFiEntry-<?php echo $edfiEntry->getId();?>label">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title" id="myModalLabel">Deleting <?php echo $connectors[$edfiEntry->connector_id]->getHostname();?> (id:<?php echo $edfiEntry->connector_id;?>)</h4>
				</div>
				<div class="modal-body">
					<p>Are you sure you want to delete the EdFi Entry <?php echo $connectors[$edfiEntry->connector_id]->getHostname(); ?></p>
					<?php
		/**
		 *
		 * @var $this->formyform \Admin\Form\AddConnectorToUserForm
		 */
		$this->deleteEdFiEntryForm->setData(array(
			'edfi-entry-id' => $edfiEntry->getId()
		));
		echo $this->formCollection($this->deleteEdFiEntryForm);
		?>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
					<button type="submit"
						class="btn btn-primary submit-button has-spinner">Yes</button>
				</div>
			</div>
		</div>
	</div>
	<?php
		echo $this->form(null, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->closeTag($this->deleteEdFiEntryForm);?>
	<?php } ?>


</section>
