

<h1>NSAP Login</h1>


<p>Welcome to the Nebraska Schools Account Provisioning application. This system allows a user to claim an account and reset password. To enter the application, please select your school district's user directory below, and type in your username and password. If you do not have access to the account, please click on the claim account tab above.</p>


<center><img src="nsapimage.png" alt="" style="width:220px;height:220px;"></center>

<br><br>

 <form action="demo_form.asp"><center>
 <input type="text" name="email" size="35" placeholder="Email Address" required=""><br><br>
 <input type="password" name="password" size="35" placeholder="Password" required=""><br><br>
 <a href="reset_password.html">Reset Password</a><br><br>
 <input type="submit" value="Login">
</center></form> 
