<section class="col-sm-12">
	<h1 class="text-center">Password Reset</h1>
	<div class="col-sm-10 col-sm-offset-1">
        <p>Welcome to the password reset webpage. This webpage will allow you to reset
        your password for your account. To continue, please select  your school district.
         Additionally, please provide your current password, and a new password for your account. </p>
	</div>
</section>

<section class="col-sm-12">
	<div class="col-sm-3 col-sm-offset-5">
		<span class="glyphicon glyphicon-user" style ="font-size: 147px; outline: 1px solid black;" aria-hidden="true"></span>
	</div>
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
            <?php
            echo $this->form($this->formyform, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
            ?>
        </div>
	</div>
</section>

